### PR TITLE
Allow BYO header view, ability to set current date, maintain date order after a jump, long press timeline delegate callback

### PR DESCRIPTION
**Pull request by v-ken**
1. BYO header view
 - Allow hiding the built-in header view so that users can use their own header views

2. Ability to set current date
 - Expose function to set the current date in `DayView`

3. Maintain date order after a jump
 - When jumping dates (by tapping on date in header view instead of swiping), the next swipe back jumps back to the previous date before the jump, instead of the previous date in the calendar. This fixes that issue.

4. Long press in timeline view delegate callback
 - Add delegate callback when the timeline view is long pressed in an area without any events

### CODE REVIEW

**Comment by richardtop** [comment]
Hi @v-ken,
thanks for your pull request.
Everything looks good, however, I have a question about the 1st part. 
When I started CalendarKit, I wanted it to be a complete but customizable solution for the DayView calendar, so your change fits into this category.
However, now I think it would be better not to hide header, but inject own header with the help of `HeaderViewProtocol`.
I'd like to merge your pull request now, but then rewrite it to use the protocol.
So, I am curious, what kind of custom header are you planning to implement? Please, share it if you can.
If you are OK with this, I will merge your PR and create new version of the pod.

**Comment by v-ken** [comment]
Hi @richardtop,

Thanks for the quick response! I am currently integrating CalendarKit with [FSCalendar](https://github.com/WenchaoD/FSCalendar) as the header and it works really well together. When a user selects a date in FSCalendar, CalendarKit is refreshed by exposing the ability to set the current date (item 2 in original post).

Having a `HeaderViewProtocol` works too. What were you planning on having as part of the protocol? Maybe we can work on that together.

**Comment by richardtop** [comment]
I am really glad to see you using CK together with another library to get something different. Since I began developing CK, I wanted it to be modular and extensible. In other words, CalendarKit should be a foundation to a building.

Master-detail could work, however, I've found only one function dependent on the class of the `DayHeaderView`:
```Swift
dayHeaderView.selectDate(currentDate)
```
So, I think, it is possible to create a `DayHeaderViewProtocol` which guarantees that any view conforming to it is
1) An instance of UIView
2) Has `selectDate(currentDate)` method

Then, `DayView` may have a parameter in its initializer, for example, a class of the view conforming to `DayHeaderViewProtocol`, or an initialized view itself (we can look at it later).

To make any third-party header compatible with CK, the only thing needed would be to implement `DayHeaderViewProtocol`.

Still, I agree that there should be an option on hiding/showing header when needed. I'd merge this pull request as it contains finished functionality and propose implementing a custom header feature in a new one. I'll create a task for it.

**Comment by v-ken** [comment]
@richardtop Sounds good! Agree with your idea on protocols now that you've explained it.

**Comment by richardtop** [comment]
Do you think, it's better to provide a class or a initialized header to the `DayView`?
In case of class, the process is straightforward with both Standard and Custom headers.
In case of initialized header, it either should be injected or initialized inside the DayView if no header has been provided. Interested to hear your input on this, as you're  actively working with these features now. Thanks.

**Comment by v-ken** [comment]
I quite like the second option of initialised header and being able to inject custom ones as long as they conform to the `HeaderViewProtocol`.

We also need to allow the frame of the header view to be changed at runtime. E.g. with FSCalendar, changing from week view to month view and back. When the header view frame is changed, the day view should follow and always remain at the bottom of the header view.

**Comment by richardtop** [comment]
@v-ken any suggestions on 2nd feature?
The first option which comes to my mind is to subclass `DayView` and customize this behavior in the new class.

**Comment by v-ken** [comment]
Hi Richard,

We could use autolayout constraints and have CK manage the view containers while exposing the constraints publicly for further customisations.

E.g. A header container at top and a day view container at the bottom, tied together by a vertical constraint. The header container will have a height constraint that is exposed publicly. By default, the header container will contain your header view and the bottom container will contain your day view. But those views can be swapped in and out.

**Comment by richardtop** [comment]
@v-ken I'd prefer not to introduce AutoLayout to this project, as I think, it will just add an extra layer of complexity.

In your Pull Request you've added a `HeaderHeight` property. I think, it's pretty easy to accomplish this behavior by implementing conditional layout in `layoutSubviews` method.

Also, I see the problem here in incorrect architecture. `DayHeaderView` belongs and controlled by the `DayView`, but there is no separate module for the bottom part of the `DayView`. Extracting that part into a separate module (which should be pretty easy as well) will make it possible to use just that module if needed.

The `DayView` could be configured then with any top (header) and bottom parts, until they conform to the specified protocols.

Before:
image
After:
image

I would like to hear some thoughts on this approach.

**Comment by v-ken** [comment]
Hey @richardtop, your proposal looks good.

Just one suggestion regarding the naming. Since `DayView` is now acting as the overall container, maybe it shouldn't be called `DayView` anymore? Something along the lines of `CalendarKit` or `CalendarKitContainer` maybe? The pager is now acting more like the `DayView` and we could maybe call that `DayViewPagerProtocol` or something along those lines?

This will indeed cause many breaking changes. Not sure if you're ok with that side effect?

**Comment by richardtop** [comment]
@v-ken thanks for the feedback.
I didn't think about naming at this stage, but of course, it should be self-explanatory.
About breaking changes - DayView will still have all the interfaces it has now, so breaking changes should be minimal. Even if there are breaking changes, the v is `0.1` and under development...

**Pull request merged**
