### PR TITLE
Allow injection of custom header

### PR DESCRIPTION
**Pull request by richardtop**
As discussed in #33,

1. I've split responsibility between two entities (which may be represented by instance of one class): `dayHeaderController` and `dayHeaderView`

The `controller` is responsible for implementing appropriate protocols for changing date, style and assigning a delegate, while `view` could be just a subclass of an `UIView`. 

These objects could be independent entities (i.e. let's say `HeaderViewController` and `HeaderViewController.view`, but also that responsibility could be in one class, like currently in `DayHeaderView`

2. To enforce that either both of the entities are nil, or both present during initialization, I've created a struct which could be initialized only with two of them.

@v-ken, please, take  a look at this approach and if it looks good, try to test with your project. Once everything is OK, we're ready to merge.

### CODE REVIEW

**Comment by v-ken** [comment]
Hey @richardtop, 

I managed to get the new style to work with my project. I had to make 2 changes to your branch though:
1. Explicit initialiser for the DayHeaderComponent as it defaults to `internal` instead of `public`.
2. Making `headerHeight` property in `DayView` public, to be able to switch week/month views.

There weren't too many changes however I think I will be sticking with my original implementation for a couple of reasons:
1. Using vertical constraints to attach both FSCalendar and CK together in Storyboard means all shrinking and expanding of week/month style is handled automatically, as opposed to setting `headerHeight` directly.
2. I also added a selected date banner view in between the header and day views which appears when the header view is scrolled and the day view is maintained at the previously selected date. This is easier to implement if both header and day views are completely separated. Refer to image below:
    screen shot 2017-03-29 at 4 26 12 pm
3. Although I don't personally use it, FSCalendar also has nice IBDesignables and IBInspectables which works well in Storyboard.

That said, I definitely see some developers who would prefer this new injection method though =)
Thanks again for this awesome library!

**Comment by richardtop** [comment]
Hi @v-ken and thanks for the comments.
The first part is clear for me, however, I have some questions regarding the second one.

Does this PR or current version of CK prevents or limits you from using your approach of combining two headers? 

I really see the need in decoupling the bottom part into a separate view, so you will be able to use only the bottom part of the CK without the header at all as in the case you've shown.

**Comment by v-ken** [comment]
Hey @richardtop, current version was easier to implement the blue banner as they are just separate views in the storyboard. PR version doesn't seem as trivial as the views are now managed by CK (although I didn't give it a good try).

**Comment by richardtop** [comment]
@v-ken OK, then let's leave it as it is.

**Pull request closed without merging**
