### PR TITLE
Feature/custom timeline view

### PR DESCRIPTION
**Pull request by fidmor89**
This PR introduces the ability to provide a `customView` instead of the `timelinePagerView`.

### CODE REVIEW

**Comment by richardtop** [comment]
Please, create a different class for the example (i.e. the third one)

**Comment by fidmor89** [comment]
Added `ExampleCustomTimeLineController.swift`

**Comment by richardtop** [comment]
Hi, after looking at your pull request, I think that the best way to achieve the design you want would be to subclass the `DayView` and introduce the change only in your code base.

This fits the philosophy behind CalendarKit - to have a ready-made templates for the common use-cases and give enough flexibility to allow creation of a highly customizable design when needed.

So, the steps I'd recommend you to take are:
1. Cancel this pull request (feel free to create an issue for further discussion)
2. Subclass `DayView` and implement your feature only available for your codebase.

I.e., instead of adding this functionality to the `DayView`, create `MyCustomDayView`:

```Swift
public class MyCustomDayView: DayView {
// Implement your feature here
}
```

This approach has two benefits:
1. you'll always keep the up-to-date version of the CalendarKit
2. You'll have greater flexibility in customizing your app's look than trying to push needed changed through the main CalendarKit repo, since not all customizations needed to your particular project fit well into  a generic calendar code.


Moreover, if you feel that the CalendarKit doesn't give you much customization, you can create your own view using the CalendarKit components (they're available when you import the library as well). That was also the intention when I've started this library.

Let me know, if you succeed in getting your feature work via subclassing.

**Comment by fidmor89** [comment]
@richardtop Thanks. I'll give it a try.

**Pull request closed without merging**
